//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUENTAS_POR_PAGAR_JABES_23EIST6015
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURASJABES23EIST6015
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURASJABES23EIST6015()
        {
            this.CHEQUESJABES23EIST6015 = new HashSet<CHEQUESJABES23EIST6015>();
        }
    
        public int NUMEROFACTURA { get; set; }
        public string CODIGO { get; set; }
        public Nullable<decimal> VALORFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAFACTURA { get; set; }
        public Nullable<System.DateTime> FECHAVENCIMIENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHEQUESJABES23EIST6015> CHEQUESJABES23EIST6015 { get; set; }
        public virtual PROVEEDORESJABES23EIST6015 PROVEEDORESJABES23EIST6015 { get; set; }
    }
}
